### ISSUE TITLE
tfoot and th elements are not behaving in parent-child relationship??

### ISSUE THREAD

**Issue by lokesh932338** [lokesh932338/web_development#1]
In the file web_development/learning_basics/practice_table.html, on line 25 th element in tfoot is styled using descendent combinator but when styled using child combinator, it fails.

**Comment by SAGARSINGH-1** [comment]
assign me this issues.

**Comment by SAGARSINGH-1** [comment]
there is a small issue in your code : 
1.Since your th and td elements within the tfoot are not immediate children of tfoot but are wrapped within a tr, using the child combinator directly on the tfoot won't select them.
2.This wouldn't work because th is not an immediate child of tfoot, it's a child of tr which is a child of tfoot.

**Comment by lokesh932338** [comment]
> there is a small issue in your code : 
> 1.Since your th and td elements within the tfoot are not immediate children of tfoot but are wrapped within a tr, using the child combinator directly on the tfoot won't select them.
> 2.This wouldn't work because th is not an immediate child of tfoot, it's a child of tr which is a child of tfoot.

th and td elements are not wrapped in tr, they are immediate child of tfoot at line 93..?

**Comment by SAGARSINGH-1** [comment]
by default added like this : <tfoot>
    //<tr>
      //<th scope="row">Totals</th>
      //<td>21,000</td>
    //</tr>
  //</tfoot>*/

**Comment by SAGARSINGH-1** [comment]
by default added like this :
("")

**Comment by lokesh932338** [comment]
does it mean, even if tr element is not there, it is believed to be there??

**Comment by SAGARSINGH-1** [comment]
yes read mdn for html tags cleareance

**Comment by lokesh932338** [comment]
> yes read mdn for html tags cleareance

ok
